workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      android_signing:
        - Nikapp
      groups:
        - google_credentials
    scripts:
      - name: Set up Java version
        script: |
          sudo apt-get update
          sudo apt-get install openjdk-17-jdk
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
      
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - bharadwajnk6@gmail.com
